In [5]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Implements the supervised gradident-based learning algorithm specified by 
Reyes-Galaviz et al. (2017).

"""

import numpy as np

input_count = 8 
hidden_count = 5 
output_count = 1

eta = 0.8

data = np.load("record_pairs.npy")
data2 = np.nan_to_num(data)

# Quality thresholds
tau_1 = 0.4
tau_2 = 0.7

# The MLP model has 8 inputs and 5 nodes in the hidden layer. It follows 
# the Model 2 setup presented by Reyes-Galaviz et al. Hidden nodes aggregate
# values calculated by running each of 8 comparison functions over 5 data
# fields (date, ISBN, title, creator, contributor)
r = np.random.randn(input_count, hidden_count)
w = np.random.randn(hidden_count, output_count)

# Sigmoid activation function
def activate(a):
    return 1 / (1 + np.exp(-a))

# Partial derivatives for output layer
def Q_tau_1(s):    
    return np.sum(s**2)

def Q_tau_2(s):
    return np.sum((1 - s)**2)

def Q(d, s, tau_1, tau_2):
    if d[5:6, 1:2] == 0:        
        return Q_tau_1(s)
    else:
        return Q_tau_2(s)

def dQ_ds(d, s, tau_1, tau_2):    
    if d[5:6, 1:2] == 0:        
        return 2 * s
    else:
        return 2 * (s - 1)        

def ds_dl(s):
    return s * (1 - s)

# Partial derivatives for hidden layer
def dy_dp(y):
    return y * (1 - y)

# 150 iterations for training model
for i in range(1):      
    
    for u in data2:
    
        # Net input of hidden layer
        p = np.dot(u[:5, :], r)        
        
        # Activation of hidden layer
        y = activate(p)
        
        # Net input of output node
        l = np.dot(y, w)        
        
        # Activation of output node
        s = activate(l)              
        
        # Chain of partial derivatives for Model 2
        # dQ_ds = dQ_ds(u, s, tau_1, tau_2)
        # ds_dl = ds_dl(s)
        dl_dw = y.T
        dl_dy = w.T
        # dQ_dl = dQ_ds * ds_dl
        dQ_dy = dQ_dl * dl_dy        
        # dy_dp = dy_dp(y)
        dp_dr = u[:5, :].T
        
        # Back propogate                
        dQ_dw = np.dot(dl_dw, (dQ_ds(u, s, tau_1, tau_2) * ds_dl(s)))        
        dQ_dr = np.dot(dp_dr, (dQ_ds(u, s, tau_1, tau_2) * ds_dl(s) * dl_dy * dy_dp(y)))        
                             
        r -= dQ_dr * eta              
        w -= dQ_dw * eta

        print(np.sum(ds_dl(s)), u[5:6, 1:2])
        



[[ 0.21988951]
 [ 0.2193063 ]
 [ 0.22396428]
 [ 0.22674484]
 [ 0.22450872]] [[ 0.]]
[[ 0.12045428]
 [ 0.15648698]
 [ 0.15988987]
 [ 0.15648698]
 [ 0.15648698]] [[ 0.]]
[[ 0.10038094]
 [ 0.13184279]
 [ 0.13716596]
 [ 0.13184279]
 [ 0.13184279]] [[ 0.]]
[[ 0.11574509]
 [ 0.11574509]
 [ 0.1220383 ]
 [ 0.11574509]
 [ 0.11574509]] [[ 0.]]
[[ 0.08025924]
 [ 0.08025924]
 [ 0.09497902]
 [ 0.1029602 ]
 [ 0.1029602 ]] [[ 1.]]
[[ 0.15826253]
 [ 0.15826253]
 [ 0.16892786]
 [ 0.16766146]
 [ 0.16766146]] [[ 1.]]
[[ 0.24959473]
 [ 0.24959473]
 [ 0.24991892]
 [ 0.24626541]
 [ 0.24626541]] [[ 1.]]
[[ 0.16392004]
 [ 0.16392004]
 [ 0.17010215]
 [ 0.21723671]
 [ 0.21723671]] [[ 1.]]
[[ 0.11406564]
 [ 0.13008311]
 [ 0.13514672]
 [ 0.18286017]
 [ 0.18286017]] [[ 1.]]
[[ 0.09501305]
 [ 0.1125955 ]
 [ 0.11660259]
 [ 0.15965886]
 [ 0.15965886]] [[ 1.]]
[[ 0.10104297]
 [ 0.10104297]
 [ 0.10426454]
 [ 0.14312773]
 [ 0.14312773]] [[ 1.]]
[[ 0.07373922]
 [ 0.13055874]
 [ 0.09371758]
 [ 0.09309658]
 [ 0.13055874]] 