In [3]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Implements the supervised gradident-based learning algorithm specified by 
Reyes-Galaviz et al. (2017).

"""

import numpy as np

input_count = 8 
hidden_count = 5 
output_count = 1

eta = 0.8

data = np.load("record_pairs.npy")
data2 = np.nan_to_num(data)

# Quality thresholds
tau_1 = 0.4
tau_2 = 0.7

# The MLP model has 8 inputs and 5 nodes in the hidden layer. It follows 
# the Model 2 setup presented by Reyes-Galaviz et al. Hidden nodes aggregate
# values calculated by running each of 8 comparison functions over 5 data
# fields (date, ISBN, title, creator, contributor)
r = np.random.randn(input_count, hidden_count)
w = np.random.randn(hidden_count, output_count)

# Sigmoid activation function
def activate(a):
    return 1 / (1 + np.exp(-a))

# Partial derivatives for output layer
def Q_tau_1(s):    
    return np.sum(s**2)

def Q_tau_2(s):
    return np.sum((1 - s)**2)

def Q(d, s, tau_1, tau_2):
    if d[5:6, 1:2] == 0:        
        return Q_tau_1(s)
    else:
        return Q_tau_2(s)

def dQ_ds(d, s, tau_1, tau_2):    
    if d[5:6, 1:2] == 0:        
        return 2 * s
    else:
        return 2 * (s - 1)        

def ds_dl(s):
    return s * (1 - s)

# Partial derivatives for hidden layer
def dy_dp(y):
    return y * (1 - y)

def dp_dr(u):
    return u

# 150 iterations for training model
for i in range(1):      
    
    for u in data2:
    
        # Net input of hidden layer
        p = np.dot(u[:5, :], r)        
        
        # Activation of hidden layer
        y = activate(p)
        
        # Net input of output node
        l = np.dot(y, w)        
        
        # Activation of output node
        s = activate(l)              
        
        # Chain of partial derivatives for Model 2
        # dQ_ds = dQ_ds(u, s, tau_1, tau_2)
        # ds_dl = ds_dl(s)
        dl_dw = y.T
        dl_dy = w.T
        # dQ_dl = dQ_ds * ds_dl
        dQ_dy = dQ_dl * dl_dy        
        # dy_dp = dy_dp(y)
        dp_dr = u[:5, :].T
        
        # Back propogate                
        dQ_dw = np.dot(dl_dw, (dQ_ds(u, s, tau_1, tau_2) * ds_dl(s)))        
        dQ_dr = np.dot(dp_dr, (dQ_ds(u, s, tau_1, tau_2) * ds_dl(s) * dl_dy * dy_dp(y)))        
                             
        r -= dQ_dr * eta              
        w -= dQ_dw * eta

        print(s, u[5:6, 1:2])
        



[[ 0.53013792]
 [ 0.63932664]
 [ 0.62396692]
 [ 0.60422014]
 [ 0.61460398]] [[ 0.]]
[[ 0.33322621]
 [ 0.35411192]
 [ 0.36080079]
 [ 0.35411192]
 [ 0.35411192]] [[ 0.]]
[[ 0.24392214]
 [ 0.21693287]
 [ 0.23125798]
 [ 0.21693287]
 [ 0.21693287]] [[ 0.]]
[[ 0.16498262]
 [ 0.16498262]
 [ 0.18204082]
 [ 0.16498262]
 [ 0.16498262]] [[ 0.]]
[[ 0.17958527]
 [ 0.17958527]
 [ 0.23901864]
 [ 0.13565042]
 [ 0.13565042]] [[ 1.]]
[[ 0.37616437]
 [ 0.37616437]
 [ 0.35452091]
 [ 0.25591521]
 [ 0.25591521]] [[ 1.]]
[[ 0.47632833]
 [ 0.47632833]
 [ 0.47012876]
 [ 0.44894078]
 [ 0.44894078]] [[ 1.]]
[[ 0.51259511]
 [ 0.51259511]
 [ 0.51894808]
 [ 0.62808174]
 [ 0.62808174]] [[ 1.]]
[[ 0.56626087]
 [ 0.53609911]
 [ 0.54670219]
 [ 0.73017378]
 [ 0.73017378]] [[ 1.]]
[[ 0.59880948]
 [ 0.56055733]
 [ 0.57456776]
 [ 0.79405586]
 [ 0.79405586]] [[ 1.]]
[[ 0.59241537]
 [ 0.59241537]
 [ 0.6082936 ]
 [ 0.83578992]
 [ 0.83578992]] [[ 1.]]
[[ 0.67485951]
 [ 0.86460192]
 [ 0.68514106]
 [ 0.6471042 ]
 [ 0.86460192]] 